apiVersion: apps/v1
kind: Deployment #  Deployment or Service
metadata:
  name: udacity-frontend
  labels:
    app: udacity-frontend
    app.kubernetes.io/name: load-balancer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-frontend
      app.kubernetes.io/name: load-balancer-frontend
  template:
    metadata:
      labels:
        app: udacity-frontend
        app.kubernetes.io/name: load-balancer-frontend
    spec:
      containers: # Docker image source
      - name: udacity-frontend
        image: zxa011023/udacity-frontend
        ports:
        - containerPort: 8100