apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-frontend
  labels:
    run: udacity-frontend
spec:
  ports:
  - port: 4200
    protocol: TCP
  selector:
    run: udacity-frontend