apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-frontend
  labels:
    run: udacity-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    run: udacity-frontend